name: "🐛 バグ報告"
description: "casebook 以外の不具合（スクリプト・ツール等）を報告します"
title: "[Bug]: "
labels: ["bug", "infrastructure"]

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ ご注意
        このテンプレートは **casebook/ ディレクトリ外の不具合報告専用** です。  
        例：`tools/` 配下のスクリプト、リポジトリ構成、CI、メタデータ検証処理など。  

        各事例 (`casebook/` 以下) の Notebook やコードの不具合は、**投稿者の責任** において修正してください。  
        リポジトリ管理者は、事例コードに関するエラー・依存関係問題・環境依存の不具合に対応しません。  

        必要に応じて、投稿者自身による修正または Pull Request で改善を提案してください。

  - type: input
    id: component
    attributes:
      label: "対象ディレクトリまたはスクリプト"
      description: "例: tools/validate_metadata.py, .github/workflows/build.yml"
      placeholder: "例: tools/validate_metadata.py"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "不具合の内容"
      description: "発生した現象やエラーメッセージをできるだけ詳しく記載してください。"
      placeholder: "例：`validate_metadata.py` で YAML パースエラーが発生しました。"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "再現手順"
      description: "不具合が発生するまでの手順を記載してください。"
      placeholder: |
        1. 環境をセットアップする
        2. `python tools/validate_metadata.py` を実行
        3. エラーが発生する
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: "実行環境"
      description: "環境情報を記載してください。"
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11
        - ライブラリ: pyyaml 6.0.2, pandas 2.2.2
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "補足情報"
      description: "再現条件や関連するファイルなどがあれば記載してください。"
      placeholder: "例：GitHub Actions の特定バージョンでのみ発生します。"
    validations:
      required: false
