name: "🔗 リンク紹介（外部記事・事例）"
description: "note / Zenn / Qiita などの外部記事や事例を紹介します"
title: "[Link]: "
labels: ["link", "submission"]

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 リンク紹介について
        公開済みの外部記事やデータ分析事例を紹介できます。  
        紹介された記事は内容を確認のうえ、`casebook/` の関連分野に登録されます。

        **リンクURL は必須です。**  
        **記事タイトル / テーマは、リンク先にタイトルがない場合のみ記入してください。**  
        **Data sources（出典・統計データ）は必須です。**

  - type: input
    id: link
    attributes:
      label: "🔗 リンクURL（必須）"
      description: "note / Zenn / Qiita / 個人ブログ などのURLを記載してください。"
      placeholder: "https://example.com/your-article"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "📝 記事タイトル / テーマ（任意）"
      description: "リンク先にタイトルがない場合には入力してください。"
      placeholder: "例：オープンデータで見る地域経済の変化"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: "📖 概要（任意）"
      description: "記事や事例の簡単な内容説明を記載してください。"
      placeholder: "例：政府統計（e-Stat）を活用し、都道府県別のCPI動向を可視化した記事です。"
    validations:
      required: false

  - type: textarea
    id: sources
    attributes:
      label: "📊 Data sources（出典・統計データ）"
      description: "使用している統計データ・出典・APIなどを記載してください。"
      placeholder: |
        例：
        - 総務省統計局「家計調査」
        - e-Stat API（https://api.e-stat.go.jp/）
    validations:
      required: true

  - type: input
    id: domain
    attributes:
      label: "📁 分野（任意）"
      description: "関連するテーマや分野を自由に記入してください（例：教育、経済、地域、イベントなど）。"
      placeholder: "例：地域経済、教育統計、環境データ"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "🗒️ 補足情報（任意）"
      description: "記事に関する注意点や関連リンクなどがあれば記載してください。"
      placeholder: "例：掲載データは2024年版に更新予定です。"
    validations:
      required: false
