name: "🆕 New case（新規事例の追加）"
description: "casebook/{domain}/{slug}/ に新しい事例を追加します"
title: "[New Case]: "
labels: ["new-case", "submission"]

body:
  - type: markdown
    attributes:
      value: |
        ## 新規事例の追加
        事例は `casebook/{domain}/{slug}/` に配置し、**フォルダ直下の `metadata.yaml` に Data sources（出典・統計データ）を記載してください。**
        CI/レビューでは `metadata.yaml` の内容を参照して確認します。

  - type: input
    id: case_path
    attributes:
      label: "対象の事例フォルダ（必須）"
      description: "例: casebook/household/202510-yourname-analysis"
      placeholder: "casebook/{domain}/{slug}/"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "事例タイトル（任意）"
      description: "`metadata.yaml` にタイトルを記載している場合は省略できます。"
      placeholder: "例：家計調査とCPIの関係可視化（2025年版）"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: "概要（任意）"
      description: "事例の狙い・可視化内容・利用手法など。"
      placeholder: "例：家計調査の支出系列とCPIの系列を整合化し、支出と物価動向を可視化。"
    validations:
      required: false

  - type: checkboxes
    id: metadata_check
    attributes:
      label: "metadata.yaml の確認"
      description: "`case_path` 配下の `metadata.yaml` に必須項目が記載されているか確認してください。"
      options:
        - label: "`title` / `domain` / `date` / `author` を記載した"
          required: true
        - label: "**`data_sources`（出典・統計データ）を記載した**（推奨：公式名称・URL・利用規約要点）"
          required: true
        - label: "コード/記事のライセンス（`code_license` など）を記載した"
          required: false

  - type: markdown
    attributes:
      value: |
        **Data sources の扱いについて**
        - 原則：`metadata.yaml` の `data_sources` を参照します（レビュー・CIはこれを確認）。
        - 例外：やむを得ない理由で `metadata.yaml` に未記載の場合のみ、下の任意欄に記載してください。

  - type: textarea
    id: data_sources_fallback
    attributes:
      label: "Data sources（任意：metadata.yaml に未記載の場合のみ記入）"
      description: "使用している統計データ・出典・API・利用規約要点を簡潔に記載してください。"
      placeholder: |
        例：
        - 総務省統計局「家計調査」：https://www.stat.go.jp/data/kakei/index.htm
          ・出典明記が必要、加工時はその旨を記載（https://www.stat.go.jp/info/riyou.html）
        - e-Stat API：https://api.e-stat.go.jp/
    validations:
      required: false

  - type: checkboxes
    id: pr_check
    attributes:
      label: "PR 前チェック（任意）"
      description: "再現性とセキュリティの観点から推奨される自己確認です。"
      options:
        - label: "Notebook の不要な実行結果をクリアした（Restart & Clear Outputs）"
          required: false
        - label: "外部データファイルを含めない（API等で再取得可能）"
          required: false
        - label: "API Key を Notebook や環境ファイルに含めていない"
          required: false
